import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { GoogleOAuthProvider } from "@react-oauth/google";
import Header from "@/components/Header";
import BottomNav from "@/components/BottomNav";
import ClientLayout from "@/components/ClientLayout";
import AppInitializer from "@/components/AppInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Missland",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleOAuthProvider
          clientId={
            "665407123210-20j9tne8tqgfi5t7dn6jr6taj51o0elk.apps.googleusercontent.com"
          }
        >
          <AuthProvider>
            <AppInitializer>
              <div className="fixed top-0 left-0 w-full h-screen bg-gradient-to-r from-pink-50 to-blue-50 -z-10" />
              <div className="relative min-h-screen">
                <div className="flex flex-col bg-transparent">
                  <Header />
                  <main className="flex-1">
                    <ClientLayout>{children}</ClientLayout>
                  </main>
                  <BottomNav />
                </div>
              </div>
            </AppInitializer>
          </AuthProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
