import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { GoogleOAuthProvider } from "@react-oauth/google";
import Header from "@/components/Header";
import BottomNav from "@/components/BottomNav";
import ClientLayout from "@/components/ClientLayout";
import { SearchProvider } from "@/context/SearchContext";
import { NavigationProvider } from "@/context/NavigationContext";
import AppInitializer from "@/components/AppInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Missland",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleOAuthProvider
          clientId={
            "665407123210-20j9tne8tqgfi5t7dn6jr6taj51o0elk.apps.googleusercontent.com"
          }
        >
          <AuthProvider>
            <SearchProvider>
              <NavigationProvider>
                <AppInitializer>
                  <div className="flex flex-col bg-white min-h-screen">
                    <Header />
                    <ClientLayout>{children}</ClientLayout>
                    <div className="md:pb-0 pb-20">
                      <BottomNav />
                    </div>
                  </div>
                </AppInitializer>
              </NavigationProvider>
            </SearchProvider>
          </AuthProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
