# Generated by Django 5.2.4 on 2025-11-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100, unique=True)),
                ('shape', models.CharField(blank=True, max_length=50)),
                ('shape_confidence', models.FloatField(default=0.0)),
                ('shape_source', models.CharField(blank=True, max_length=50)),
                ('pattern', models.CharField(blank=True, max_length=50)),
                ('pattern_confidence', models.FloatField(default=0.0)),
                ('pattern_source', models.CharField(blank=True, max_length=50)),
                ('colors', models.JSONField(default=list)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('num_nails_detected', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
