# Generated by Django 5.2.4 on 2025-11-09 12:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0016_user_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TryOnSession",
            fields=[
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nail_reference_image",
                    models.ImageField(
                        blank=True,
                        help_text="Uploaded nail reference image (alternative to post)",
                        null=True,
                        upload_to="try_on/references/%Y/%m/%d/",
                    ),
                ),
                (
                    "source_image",
                    models.ImageField(
                        blank=True,
                        help_text="Uploaded hand image (optional, alternative to camera)",
                        null=True,
                        upload_to="try_on/sources/%Y/%m/%d/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initializing", "Initializing"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="initializing",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Session expiration time (typically 30 minutes)"
                    ),
                ),
                (
                    "stats",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Session statistics: frames processed, FPS, latency, etc.",
                    ),
                ),
                (
                    "nail_reference_post",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nail post selected from explore page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tryon_sessions",
                        to="core.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this session",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tryon_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Try-On Session",
                "verbose_name_plural": "Try-On Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TryOnResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processed_image",
                    models.ImageField(
                        help_text="Final try-on result image with overlay",
                        upload_to="try_on/results/%Y/%m/%d/",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail for grid display",
                        null=True,
                        upload_to="try_on/thumbnails/%Y/%m/%d/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="AI model confidence score (0.0-1.0)",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detection info: hands detected, fingertips, etc.",
                    ),
                ),
                (
                    "nail_reference_post",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original nail post reference",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who captured this result",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tryon_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Session this result was captured from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="try_on.tryonsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Try-On Result",
                "verbose_name_plural": "Try-On Results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tryonsession",
            index=models.Index(
                fields=["user", "status"], name="try_on_tryo_user_id_e77e4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tryonsession",
            index=models.Index(
                fields=["created_at"], name="try_on_tryo_created_e97c54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tryonsession",
            index=models.Index(
                fields=["expires_at"], name="try_on_tryo_expires_58ac98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tryonresult",
            index=models.Index(
                fields=["user", "created_at"], name="try_on_tryo_user_id_3d485f_idx"
            ),
        ),
    ]
