# Generated by Django 5.2.4 on 2025-07-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='height',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='post',
            name='width',
            field=models.IntegerField(default=400),
        ),
    ]
