# Generated by Django 5.2.4 on 2025-07-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_height_post_width'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
