# Generated by Django 5.2.4 on 2025-07-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.JSONField(blank=True, default=dict, help_text="A dictionary of tags like {'color': 'red', 'style': 'short'}"),
        ),
    ]
