# Generated by Django 5.2.4 on 2025-07-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="A list of tags like ['red', 'short', 'gel']"),
        ),
    ]
