# Generated by Django 5.2.4 on 2025-10-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='colors',
        ),
        migrations.AddField(
            model_name='post',
            name='pattern',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='shape',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='size',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
