# Generated by Django 5.2.4 on 2025-11-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_tags_post_colors_post_pattern_post_shape_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='saves_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['shape', 'pattern'], name='post_shape_pattern_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['shape', 'size'], name='post_shape_size_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='post_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-views_count'], name='post_views_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-saves_count'], name='post_saves_desc_idx'),
        ),
    ]
