# Generated by Django 5.2.4 on 2025-11-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_rename_tags_post_colors_post_pattern_post_shape_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPERUSER", "Superuser"),
                    ("ADMIN", "Admin"),
                    ("ANNOTATOR", "Annotator"),
                    ("USER", "User"),
                ],
                default="USER",
                max_length=20,
            ),
        ),
    ]
