# Generated by Django 5.2.4 on 2025-11-18 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_post_options_post_saves_count_post_views_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('device_name', models.CharField(help_text="Device name (e.g., 'iPhone 14', 'Chrome on MacBook')", max_length=255)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('os_name', models.CharField(blank=True, help_text="Operating system (e.g., 'iOS 17', 'Windows 11')", max_length=100)),
                ('browser_name', models.CharField(blank=True, help_text="Browser (e.g., 'Chrome', 'Safari')", max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent_hash', models.CharField(blank=True, db_index=True, help_text='Hash of User-Agent for additional security', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this session is still valid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='usersession_user_active_idx')],
            },
        ),
    ]
